src:
- src/*
- .gitattributes
- .gitignore

docs:
- _config.yml
- _layouts/*
- assets/*
- 404.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE.md
- README.md
- SECURITY.md

docker:
- .dockerignore
- Dockerfile
- docker-compose.yml

github:
- .github/*
