theme: jekyll-theme-minimal
title: Janus Gateway Docker
description: Docker for Janus, the general purpose WebRTC server.
logo: "android-chrome-512x512.png"
show_downloads: true
# google_analytics: [Your Google Analytics tracking ID]
